#!/usr/bin/env bash

## ~~~ Create 2023 Inqognitoo <alexinq6@gmail.com>
##
## Script to launch telegram-desktop properly.
##
## At:
##     ~/.config/bspwm/sxhkdrc
##     ~/.local/share/applications/org.telegram.desktop.desktop

XDG_CURRENT_DESKTOP=XFCE telegram-desktop &
