#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## ~~~ Edit 2023 Inqognitoo <alexinq6@gmail.com>
##
## Script to manage speaker volume on Archcraft.

icons='/usr/share/archcraft/icons/dunst'
message='dunstify -u low -h string:x-dunst-stack-tag:obvolume'

get_status(){
    local string=( "`wpctl get-volume @DEFAULT_AUDIO_SINK@`" )
    local status=( $string )

    volume=$(printf "%.0f" $(echo "${status[1]} * 100" | bc -l))
    clatch=$(expr ${#status[@]} == 3)
}

get_mic_status(){
    local string=( "`wpctl get-volume @DEFAULT_AUDIO_SOURCE@`" )
    local status=( $string )

    clatch=$(expr ${#status[@]} == 3)
}

get_icon(){
    get_status
    if [[ "$volume" -ge 60 ]]; then
        icon="$icons/volume-high.png"
    elif [[ "$volume" -ge 30 ]]; then
        icon="$icons/volume-mid.png"
    elif [[ "$volume" -gt 00 ]]; then
        icon="$icons/volume-low.png"
    else
        icon="$icons/volume-mute.png"
    fi
}

send_message(){
    get_icon
    ${message} -i "$icon" "Volume: $volume%"

}

inc_volume(){
    get_status
    if [[ $clatch -eq 1 ]]; then
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    fi
    wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 2%+
    send_message
}

dec_volume(){
    get_status
    if [[ $clatch -eq 1 ]]; then
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    fi
    wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 2%-
    send_message
}

toggle_volume(){
    get_status
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    if [[ $clatch -eq 1 ]]; then
        send_message
    else
        ${message} -i "$icons/volume-mute.png" "Mute"
    fi
}

toggle_mic(){
    get_mic_status
    wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
    if [[ $clatch -eq 1 ]]; then
 		${message} -i "$icons/microphone-mute.png" "Microphone switched OFF"
        light -Srs "sysfs/leds/platform::micmute" 1
	else
	    ${message} -i "$icons/microphone.png" "Microphone switched ON" 
        light -Srs "sysfs/leds/platform::micmute" 0
	fi
}

if [[ "$1" == "--inc" ]]; then
    inc_volume
elif [[ $1 == "--dec" ]]; then
    dec_volume
elif [[ $1 == "--toggle" ]]; then
    toggle_volume
elif [[ $1 == "--toggle-mic" ]]; then
    toggle_mic
fi

