#!/usr/bin/env bash

# Add bspwm scripts to PATH
export PATH="${PATH}:$HOME/.config/bspwm/scripts"

# Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

# Set for some desktop environment integration
# export XDG_CURRENT_DESKTOP=GNOME
