#!/usr/bin/env bash

# Clear active window rules
bspc rule -r *:*

# Set pointer motion interval for floating windows drag & move better experience
bspc config pointer_motion_interval 5

## Floating apps
declare -a floating=(
    Thunar 
    Pavucontrol 
    Blueman-manager 
    Viewnior 
    feh
    MPlayer
    Nm-connection-editor 
    Xarchiver 
    Music 
    GParted 
    Toolkit 
    firefox:Toolkit
    Rhythmbox
)

for i in ${floating[@]}; do
   bspc rule -a $i state=floating focus=on center=true; 
done

# Virtualbox overhead
#bspc rule -a "VirtualBox" state=floating center=true rectangle=1000x600+0+0 layer=normal
#bspc rule -a "VirtualBox Manager" state=floating center=true rectangle=1000x600+0+0 layer=below
#bspc rule -a "VirtualBox Machine" state=floating focus=on layer=above

# Open in certain desktop
bspc rule -a TelegramDesktop desktop='^8' follow=true
bspc rule -a discord desktop='^7' follow=true
