#!/usr/bin/env bash

# Kill active processes
killall -9 xsettingsd sxhkd dunst ksuperkey xss-lock bspc

# Lauch xsettingsd daemon
xsettingsd --config="$HOME"/.config/bspwm/xsettingsd &

# Polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Set keyboard layout switch
setxkbmap -option grp:alt_shift_toggle us,ru &

# Lauch keybindings daemon
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

# Enable super keys for rofi
ksuperkey -e 'Super_L=Alt_L|F1' &

# Enable lock screen hd
# note: it needs lid lock rules at /etc/systemd/logind*
#
xss-lock -- betterlockscreen --suspend &

# Libinput-gestures setup
libinput-gestures-setup start &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
feh --no-fehbg --bg-fill /home/inqognitoo/.config/bspwm/.images/evening-sky.png

# Start mpd
exec mpd &

# Start bspwm scripts
bspbar
bspcomp
bspdunst
